---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: postgresql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/ccma/data/postgresql-data
  persistentVolumeReclaimPolicy: Retain
