---
- name: sonarqube
  hosts: master1
  gather_facts: no

  vars: 
    ansible_become_pass: "ccma"

  tasks:
    - name: Copy multiple .yml files to remote
      copy: 
        src: "{{ item }}"
        dest: "/home/ccma/{{ item }}"
        owner: ccma
        group: ccma
        mode: 0644
      with_items:
        - sonarqube/
        - sonarqube-pv.yml
  
    - name: Initialize persistent volumes
      shell: "kubectl create -f sonarqube-pv.yml"
      environment: 
        KUBECONFIG: /home/ccma/.kube/config

    - name: Install SonarQube by Helm
      shell: "helm install --name sonarqube ./sonarqube"
      environment:
        KUBECONFIG: /home/ccma/.kube/config
      register: install_sonarqube

    - name: Debug install_sonarqube
      debug:
        var: install_sonarqube
